### ISSUE TITLE
Availablity in Maven Repository

### ISSUE THREAD

**Issue by bigkahuna1uk** [bodar/yatspec#26]
Is it possible to have this great test library available in the main mvn repository. Unfortanately I can't access the bodar repo due to firewall issues?

**Comment by danielbodart** [comment]
Short answer: Happy for you to publish it.

Long answer:

Q: Why don't you use Maven Central Repository?

A: We don't use it for a number of reasons:

 * Reliability (Single point of failure, multiple outages every year)
 * Performance (High latency, low bandwidth)
 * Unnecessary red tape (Login accounts, unneeded mandatory data required in pom.xml files, expectaction you will use Maven as your build tool)
 * Centralised (Artifact repositories should be decentralised just like their development and the rest of the internet)
 * Non-Programmable (Can't handle the number of automated releases we do every day)
 * Mutable (They allow you to republish the same version with a different binary)

Instead we use Amazon S3 for reliable storage (99.9% SLA) and Amazon CDN for super fast local delivery of artifacts. All artifacts are also duplicated to GitHubs infrastructure (releases page)

Sorry ;)

**Comment by danielbodart** [comment]
Oh we might possibly use bin tray at some future date if I can work out a way of not breaking repo.bodar.com links
