### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wojciechbulaty** [bodar/yatspec#28]
Would you be able to add a license file to the project, please? Is it Apache 2?

**Comment by danielbodart** [comment]
Done

**Comment by wojciechbulaty** [comment]
Thanks. If you wanna be strict about it you can also fill in " Copyright {yyyy} {name of copyright owner}" in that file.

**Comment by danielbodart** [comment]
Arse GitHub suggested I replaced my License (which has that correctly set)
with the "official" one. Should have ignore it.
