### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by theangrydev** [bodar/yatspec#43]
In order to get yatspec into the wider Java community, I think that releasing to central is an important step.

Some companies (e.g. banks or other locked down environments) are not able to depend on repo.bodar.com but do have access to central.

A guide on how to release there can be found here:
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by danielbodart** [comment]
Q: Why don't you use Maven Central Repository?

A: I don't use it for a number of reasons:

- Reliability (Single point of failure, multiple outages every year)
- Performance (High latency, low bandwidth)
- Unnecessary red tape (Login accounts, unneeded mandatory data required in pom.xml files, expectaction you will use Maven as your build tool)
- Unnecessary API complexity (It should just be a PUT request like any normal web server)
- Centralised (Artifact repositories should be decentralised just like their development and the rest of the internet)
- Mutable (They allow you to republish the same version with a different binary)
- Instead we use Amazon S3 for reliable storage (99.9% SLA) and CloudFlare CDN for super fast local delivery of artifacts. All artifacts are also duplicated to GitHubs infrastructure (releases page)

If someone else wants to set this up, more than happy to support it via a WebHook or TeamCity.  I know this isn't the answer you were hoping for but I hope that you can respect that other people might have different values from yourself.

**Comment by theangrydev** [comment]
How about raising an issue to mirror the artifacts to central instead then?

To meet the central [requirements](http://central.sonatype.org/pages/requirements.html), there are a few pieces that are still missing though:
* Creating a [New Project](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134) ticket on issues.sonatype.org
* Producing a Javadoc JAR
* Signing all artifacts with a GPG key

I can understand your reasons for not wanting central to be the official repo for your projects. 

I'm sure that you can also understand the problem I am trying to solve.

Some proportion of your potential users end up ruling out using your projects due to not wanting a dependency on repo.bodar.com. Personal repositories tend to be significantly less trusted in industry, which is unfortunate but just part of reality. I'm not sure if having more users is one of your goals or not, but it tends to be for people who put the effort into making a library open source in the first place.
